apiVersion: v1
kind: Secret
metadata:
  name: payment-secrets
  namespace: default
type: Opaque
stringData:
  # MONGO_URI: "mongodb+srv://root:bishru@books-store-mern.kq25k3n.mongodb.net/payment?appName=Healthcare-System"
  MONGO_URI: "mongodb+srv://root:bishru@books-store-mern.kq25k3n.mongodb.net/medico?appName=Books-Store-MERN"
  JWT_SECRET: "your_jwt_secret_here"
