apiVersion: v1
kind: Secret
metadata:
  name: payment-secrets
  namespace: healthcare
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://root:bishru@books-store-mern.kq25k3n.mongodb.net/payment?appName=Healthcare-System"
  JWT_SECRET: "your_jwt_secret_here_change_in_production"
