apiVersion: v1
kind: Secret
metadata:
  name: healthcare-secrets
  namespace: healthcare
type: Opaque
stringData:
  JWT_SECRET: your_jwt_secret_here
  CLOUD_NAME: dus7bhnd3
  CLOUD_API_KEY: "551137298448198"
  CLOUD_API_SECRET: naoKz3ikK05AvrclUHOi3kBM5zw
